// Copyright 2026 Bohdan Shtepan.
// Licensed under the MIT License.

// Code generated by go-lsp/cmd/generate; DO NOT EDIT.
// LSP version: 3.17.0

package protocol

import (
	"context"
	"go.lsp.dev/jsonrpc2"
)

// Client defines the interface for an LSP client.
// All methods correspond to LSP requests and notifications
// directed from server to client.
type Client interface {
	// CancelRequest handles the "$/cancelRequest" method.
	CancelRequest(ctx context.Context, params *CancelParams) error
	// LogTrace handles the "$/logTrace" method.
	LogTrace(ctx context.Context, params *LogTraceParams) error
	// Progress handles the "$/progress" method.
	Progress(ctx context.Context, params *ProgressParams) error
	// The `client/registerCapability` request is sent from the server to the client to register a new capability
	// handler on the client side.
	RegisterCapability(ctx context.Context, params *RegistrationParams) (any, error)
	// The `client/unregisterCapability` request is sent from the server to the client to unregister a previously registered capability
	// handler on the client side.
	UnregisterCapability(ctx context.Context, params *UnregistrationParams) (any, error)
	// The telemetry event notification is sent from the server to the client to ask
	// the client to log telemetry data.
	Event(ctx context.Context, params LSPAny) error
	// Diagnostics notification are sent from the server to the client to signal
	// results of validation runs.
	PublishDiagnostics(ctx context.Context, params *PublishDiagnosticsParams) error
	// The log message notification is sent from the server to the client to ask
	// the client to log a particular message.
	LogMessage(ctx context.Context, params *LogMessageParams) error
	// A request to show a document. This request might open an
	// external program depending on the value of the URI to open.
	// For example a request to open `https://code.visualstudio.com/`
	// will very likely open the URI in a WEB browser.
	// 
	// @since 3.16.0
	ShowDocument(ctx context.Context, params *ShowDocumentParams) (*ShowDocumentResult, error)
	// The show message notification is sent from a server to a client to ask
	// the client to display a particular message in the user interface.
	ShowMessage(ctx context.Context, params *ShowMessageParams) error
	// The show message request is sent from the server to the client to show a message
	// and a set of options actions to the user.
	ShowMessageRequest(ctx context.Context, params *ShowMessageRequestParams) (*MessageActionItem, error)
	// The `window/workDoneProgress/create` request is sent from the server to the client to initiate progress
	// reporting from the server.
	Create(ctx context.Context, params *WorkDoneProgressCreateParams) (any, error)
	// A request sent from the server to the client to modified certain resources.
	ApplyEdit(ctx context.Context, params *ApplyWorkspaceEditParams) (*ApplyWorkspaceEditResult, error)
	// A request to refresh all code actions
	// 
	// @since 3.16.0
	WorkspaceCodeLensRefresh(ctx context.Context) (any, error)
	// The 'workspace/configuration' request is sent from the server to the client to fetch a certain
	// configuration setting.
	// 
	// This pull model replaces the old push model were the client signaled configuration change via an
	// event. If the server still needs to react to configuration changes (since the server caches the
	// result of `workspace/configuration` requests) the server should register for an empty configuration
	// change event and empty the cache if such an event is received.
	Configuration(ctx context.Context, params *ConfigurationParams) ([]LSPAny, error)
	// The diagnostic refresh request definition.
	// 
	// @since 3.17.0
	WorkspaceDiagnosticRefresh(ctx context.Context) (any, error)
	// @since 3.17.0
	WorkspaceInlayHintRefresh(ctx context.Context) (any, error)
	// @since 3.17.0
	WorkspaceInlineValueRefresh(ctx context.Context) (any, error)
	// @since 3.16.0
	WorkspaceSemanticTokensRefresh(ctx context.Context) (any, error)
	// The `workspace/workspaceFolders` is sent from the server to the client to fetch the open workspace folders.
	WorkspaceFolders(ctx context.Context) ([]WorkspaceFolder, error)
}

type clientDispatcher struct {
	conn jsonrpc2.Conn
	logger Logger
}

// ClientDispatcher returns a Client that dispatches LSP requests/notifications
// across the given jsonrpc2 connection.
//
// The logger parameter is used for protocol-level logging. Pass NopLogger()
// (or nil) to disable logging.
func ClientDispatcher(conn jsonrpc2.Conn, logger Logger) Client {
	if logger == nil {
		logger = NopLogger()
	}
	return &clientDispatcher{conn: conn, logger: logger}
}

func (c *clientDispatcher) CancelRequest(ctx context.Context, params *CancelParams) error {
	return c.conn.Notify(ctx, "$/cancelRequest", params)
}

func (c *clientDispatcher) LogTrace(ctx context.Context, params *LogTraceParams) error {
	return c.conn.Notify(ctx, "$/logTrace", params)
}

func (c *clientDispatcher) Progress(ctx context.Context, params *ProgressParams) error {
	return c.conn.Notify(ctx, "$/progress", params)
}

func (c *clientDispatcher) RegisterCapability(ctx context.Context, params *RegistrationParams) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "client/registerCapability", params, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) UnregisterCapability(ctx context.Context, params *UnregistrationParams) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "client/unregisterCapability", params, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) Event(ctx context.Context, params LSPAny) error {
	return c.conn.Notify(ctx, "telemetry/event", params)
}

func (c *clientDispatcher) PublishDiagnostics(ctx context.Context, params *PublishDiagnosticsParams) error {
	return c.conn.Notify(ctx, "textDocument/publishDiagnostics", params)
}

func (c *clientDispatcher) LogMessage(ctx context.Context, params *LogMessageParams) error {
	return c.conn.Notify(ctx, "window/logMessage", params)
}

func (c *clientDispatcher) ShowDocument(ctx context.Context, params *ShowDocumentParams) (*ShowDocumentResult, error) {
	var result ShowDocumentResult
	_, err := c.conn.Call(ctx, "window/showDocument", params, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *clientDispatcher) ShowMessage(ctx context.Context, params *ShowMessageParams) error {
	return c.conn.Notify(ctx, "window/showMessage", params)
}

func (c *clientDispatcher) ShowMessageRequest(ctx context.Context, params *ShowMessageRequestParams) (*MessageActionItem, error) {
	var result MessageActionItem
	_, err := c.conn.Call(ctx, "window/showMessageRequest", params, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *clientDispatcher) Create(ctx context.Context, params *WorkDoneProgressCreateParams) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "window/workDoneProgress/create", params, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) ApplyEdit(ctx context.Context, params *ApplyWorkspaceEditParams) (*ApplyWorkspaceEditResult, error) {
	var result ApplyWorkspaceEditResult
	_, err := c.conn.Call(ctx, "workspace/applyEdit", params, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *clientDispatcher) WorkspaceCodeLensRefresh(ctx context.Context) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "workspace/codeLens/refresh", nil, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) Configuration(ctx context.Context, params *ConfigurationParams) ([]LSPAny, error) {
	var result []LSPAny
	_, err := c.conn.Call(ctx, "workspace/configuration", params, &result)
	if err != nil {
		var zero []LSPAny
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) WorkspaceDiagnosticRefresh(ctx context.Context) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "workspace/diagnostic/refresh", nil, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) WorkspaceInlayHintRefresh(ctx context.Context) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "workspace/inlayHint/refresh", nil, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) WorkspaceInlineValueRefresh(ctx context.Context) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "workspace/inlineValue/refresh", nil, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) WorkspaceSemanticTokensRefresh(ctx context.Context) (any, error) {
	var result any
	_, err := c.conn.Call(ctx, "workspace/semanticTokens/refresh", nil, &result)
	if err != nil {
		var zero any
		return zero, err
	}
	return result, nil
}

func (c *clientDispatcher) WorkspaceFolders(ctx context.Context) ([]WorkspaceFolder, error) {
	var result []WorkspaceFolder
	_, err := c.conn.Call(ctx, "workspace/workspaceFolders", nil, &result)
	if err != nil {
		var zero []WorkspaceFolder
		return zero, err
	}
	return result, nil
}

